# Generated by Django 5.0.3 on 2024-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_random',
            field=models.IntegerField(default='0'),
        ),
    ]
