# Generated by Django 5.0.4 on 2024-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_account_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='puzzles_finished',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
